@startuml
== 客户端（10.240.89.99） 发送获取指定页面请求，服务端确认已经收到请求数据  ==
客户端 --> 服务端: [ACK PUSH] seq=1 ack=1 len=2166
服务端 --> 客户端: [ACK] seq=1 ack=1449 len=0
服务端 --> 客户端: [ACK] seq=1 ack=2167 len=0

== 服务端（47.95.47.253）向客户端（10.240.89.99）推送两次数据，客户端对收到的数据进行确认  ==
服务端 --> 客户端: [ACK] seq=1 ack=2167 len=1448
服务端 --> 客户端: [ACK] seq=1449 ack=2167 len=1448
客户端 --> 服务端: [ACK] seq=2167 ack=2897 len=0

== 服务端（47.95.47.253）再向客户端（10.240.89.99）两次推送数据，客户端对收到的数据进行确认  ==
服务端 --> 客户端: [ACK] seq=2897 ack=2167 len=1448
服务端 --> 客户端: [ACK] seq=4345 ack=2167 len=1448
客户端 --> 服务端: [ACK] seq=2167 ack=5793 len=0
== 后面还有以上的二次类似操作，这里略  ==

== 服务端（47.95.47.253）最后向客户端（10.240.89.99）两次推送数据，客户端对收到的数据进行确认 ==
服务端 --> 客户端: [ACK] seq=11585 ack=2167 len=1448
服务端 --> 客户端: [ACK] seq=13033 ack=2167 len=1085
客户端 --> 服务端: [ACK] seq=2167 ack=14118 len=0


@enduml