// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/stream/route_guide.proto

package com.hry.spring.grpc.stream;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional .Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>optional .Point location = 2;</code>
   */
  com.hry.spring.grpc.stream.Point getLocation();
  /**
   * <code>optional .Point location = 2;</code>
   */
  com.hry.spring.grpc.stream.PointOrBuilder getLocationOrBuilder();
}
