// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/stream/route_guide.proto

package com.hry.spring.grpc.stream;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  java.util.List<Feature>
      getFeatureList();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  Feature getFeature(int index);
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  java.util.List<? extends FeatureOrBuilder>
      getFeatureOrBuilderList();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  FeatureOrBuilder getFeatureOrBuilder(
          int index);
}
