// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/stream/route_guide.proto

package com.hry.spring.grpc.stream;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 latitude = 1;</code>
   */
  int getLatitude();

  /**
   * <code>optional int32 longitude = 2;</code>
   */
  int getLongitude();
}
