// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/stream/route_guide.proto

package com.hry.spring.grpc.stream;

public final class RouteGuideEntity {
  private RouteGuideEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FeatureDatabase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n?src/main/resources/com/hry/spring/grpc" +
      "/stream/route_guide.proto\",\n\005Point\022\020\n\010la" +
      "titude\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005\"3\n\tRecta" +
      "ngle\022\022\n\002lo\030\001 \001(\0132\006.Point\022\022\n\002hi\030\002 \001(\0132\006.P" +
      "oint\"1\n\007Feature\022\014\n\004name\030\001 \001(\t\022\030\n\010locatio" +
      "n\030\002 \001(\0132\006.Point\"6\n\tRouteNote\022\030\n\010location" +
      "\030\001 \001(\0132\006.Point\022\017\n\007message\030\002 \001(\t\"b\n\014Route" +
      "Summary\022\023\n\013point_count\030\001 \001(\005\022\025\n\rfeature_" +
      "count\030\002 \001(\005\022\020\n\010distance\030\003 \001(\005\022\024\n\014elapsed" +
      "_time\030\004 \001(\005\",\n\017FeatureDatabase\022\031\n\007featur",
      "e\030\001 \003(\0132\010.Feature2\255\001\n\nRouteGuide\022 \n\nGetF" +
      "eature\022\006.Point\032\010.Feature\"\000\022(\n\014ListFeatur" +
      "es\022\n.Rectangle\032\010.Feature\"\0000\001\022(\n\013RecordRo" +
      "ute\022\006.Point\032\r.RouteSummary\"\000(\001\022)\n\tRouteC" +
      "hat\022\n.RouteNote\032\n.RouteNote\"\000(\0010\001B0\n\032com" +
      ".hry.spring.grpc.streamB\020RouteGuideEntit" +
      "yP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Point_descriptor,
        new String[] { "Latitude", "Longitude", });
    internal_static_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rectangle_descriptor,
        new String[] { "Lo", "Hi", });
    internal_static_Feature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Feature_descriptor,
        new String[] { "Name", "Location", });
    internal_static_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteNote_descriptor,
        new String[] { "Location", "Message", });
    internal_static_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteSummary_descriptor,
        new String[] { "PointCount", "FeatureCount", "Distance", "ElapsedTime", });
    internal_static_FeatureDatabase_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_FeatureDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FeatureDatabase_descriptor,
        new String[] { "Feature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
