// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/stream/route_guide.proto

package com.hry.spring.grpc.stream;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>optional .Point location = 1;</code>
   */
  com.hry.spring.grpc.stream.Point getLocation();
  /**
   * <code>optional .Point location = 1;</code>
   */
  com.hry.spring.grpc.stream.PointOrBuilder getLocationOrBuilder();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
