// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/mystream/hello_stream.proto

package com.hry.spring.grpc.mystream;

public interface SimpleListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  java.util.List<Simple>
      getSimpleListList();
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  Simple getSimpleList(int index);
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  int getSimpleListCount();
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  java.util.List<? extends SimpleOrBuilder>
      getSimpleListOrBuilderList();
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  SimpleOrBuilder getSimpleListOrBuilder(
          int index);
}
