// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/com/hry/spring/grpc/mystream/hello_stream.proto

package com.hry.spring.grpc.mystream;

public interface SimpleFeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleFeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  java.util.List<com.hry.spring.grpc.mystream.SimpleFeature> 
      getFeatureList();
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  com.hry.spring.grpc.mystream.SimpleFeature getFeature(int index);
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  java.util.List<? extends com.hry.spring.grpc.mystream.SimpleFeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  com.hry.spring.grpc.mystream.SimpleFeatureOrBuilder getFeatureOrBuilder(
      int index);
}
